마이페이지: 기분 별 일기조회
2023-Capstone/capstone-front pull request #17
Opened 2023-05-30 08:22 UTC by rewritestar

### 데모페이지
https://magical-mousse-034e3a.netlify.app/me?t=diary

- Mock 서버를 제 포스트맨으로 연결해서 만든 데모페이지입니다. 
데모페이지로 실행하게되면, 포스트맨 사용이 미흡해서, 
일기 개수를 정확하게 맞추지는 못해서 무조건 10개 단위로 나오는데, 
실제 코드 내에서 npm으로 실행하시면, 데이터 베이스에서 일기 가져오는 API 그대로 msw에 구현해서, 
백엔드와 실제로 연결한 것이랑 거의 동일하게 시험해보실 수 있습니다.

- 페이지네이션 버튼 부분을 10개 단위(총 100페이지)로 나누어서 보여주려고 했기에, 
버튼 부분 생성하는 로직 때문에 Pagnation 파일이 조금 복잡해요.
최대한 가능한 경우의 수는 다 확인하고 오류 없다고 판단하고 올려봅니다..

- 이전버튼(<<), 다음버튼(>>)은 한 페이지씩 이동하는 것이 아닌, 10개 단위로 넘길 수 있는 기능으로 만들었습니다.

- [ ] #16

2023-05-31 04:34 UTC, Pridesd reviewed
고생하셔습니다~~

2023-05-31 04:34 UTC, Pridesd commented on src/constants/diary.js
> +export { EMOTION };
오 이거는 에디터에서도 사용할 수 있을 것 같아서 EMOTION보다는 MOOD로 바꾸면 좋을 것 같습니당

2023-05-31 04:34 UTC, Pridesd commented on src/pages/Mypage/Diary/Post/Pagination/index.jsx
> +const LIMIT = 10;
이거도 constants에 빼놓는 건 어떠신지,,

2023-05-31 11:33 UTC, rewritestar commented on src/constants/diary.js
> +export { EMOTION };
네네!

2023-06-01 04:55 UTC, LAH1203 requested changes
모바일 구현 추가하실 줄 알았는데 안되어 있네요... 가능하시다면 이번 pr에서 추가해주세요.

추가적으로 에러랑 고쳐야 할 부분들은 코멘트로 달았습니다.
그리고 저번 pr부터 네이밍 관련해서 이해할 수 없는 부분이 너무 많아요. 저도 예전부터 꾸준히 들어왔던 지적이라 조금씩 고치고 있는데, 인미님한테도 한 번 조언 드려봅니다..!
리팩토링 필요한 부분도 많아보여요. 저희는 단순히 완성만 하고 끝이지만 실제 프로세스를 경험해보는 입장에서 유지보수를 고려하고 프로젝트를 진행하면 좋을 것 같다고 생각했어요. 근데 지금 코드는 제가 실제로 이해하지 못해서 리뷰를 포기한 부분도 있고, 이해하려고 한 컴포넌트만 10분 넘게 본 것도 있어요. 물론 제가 이해력이 딸려서 그런 것일 수도 있지만, 어느 기업을 가든 혼자 코딩하는 게 아닌 이상 다른 사람을 이해시키는 코드를 짜야한다고 생각해요. 제 경험 상 자신이 짠 코드여도 못 짠 코드는 몇 달이 지나면 자신도 이해하지 못하는 코드가 되곤 했거든요. 기능을 구현하는 것도 중요하지만 그만큼 보기 좋은 코드를 짜는 것도 중요하다고 생각합니다. 그런 부분을 고려하면서 코딩하시면 실력도 많이 향상되실거예요!

물론 제가 쓴 소리만 해서 그렇지, 좋은 부분도 여럿 보여요 🙂 가장 좋다고 생각되는 부분은 통일성인데요. 인미님 코드는 자신만의 기준을 잡고 그 기준에 맞게 코딩하는 것 같다고 생각이 들었어요. 예를 들면 `Wrapper**` 같은 거라든가? 사실 가독성에 있어서 통일성은 크게 상관 없어보이지만, 중요한 요소 중에 하나예요. 나랑 다른 기준이더라도 이런 기준으로 짰구나를 인지하면 다른 코드를 볼 때도 이런 의도구나, 또는 이런 식으로 짠 거구나 이해하기 좀 더 수월하거든요. 다만 그 기준이 팀에서 혼자 독창적이면 팀 코드지만 그 사람의 코드는 섞이지 못하게 되겠죠 🥲 그래서 통일성은 중요하지만 기준에 팀에 맞게! 가 중요한 것 같아요.

2023-06-01 04:55 UTC, LAH1203 commented on src/apis/request/diary.js
> +const requestDiaryByEmotion = params => {
전체적으로 기분을 emotion으로 많이 쓰셨더라고요. 근데 저희는 기분을 mood로 쓰기로 했으니 용어 통일이 필요해보여요! api path나 등등 모든 곳에 적용되는 사항입니다. 용어 통일은 간단해보이지만 팀 프로젝트에서는 매우 중요한 사항이에요.

2023-06-01 04:55 UTC, LAH1203 commented on src/apis/request/diary.js
> +      `${API_PATH.DIARY_BY_EMOTION}?mood=${params.mood}&page=${params.page}&size=${params.size}`,
혹시 사이즈를 따로 보내는 이유가 있나요? 개인적으로는 사이즈가 항상 고정이라면 (다른 곳에서도 같은 api가 쓰이거나 사용자가 단위를 조절하지 않는 이상 웬만하면 고정이겠죠?) api 요청에서 이를 제외하고 프/백 협의로 이렇게 하기로 했다 정하는 게 낫다고 생각해요. size라는 게 추가됨으로써 오히려 다른 것에 집중되어야 할 시선이 분산되는 경우가 많거든요.

2023-06-01 04:55 UTC, LAH1203 commented on src/apis/request/diary.js
> +const requestDiaryByEmotion = params => {
또 지금은 기분에 관련된 일기를 가져오는 함수이니 일기를 "가져온다"라는 행위가 포함되면 좋을 것 같아요.

2023-06-01 04:55 UTC, LAH1203 commented on src/apis/request/diary.js
> +      `${API_PATH.DIARY_BY_EMOTION}?mood=${params.mood}&page=${params.page}&size=${params.size}`,
보니까 밑에 `requestDiaryNumByEmotion`이라는 함수가 있는데 여기서는 size를 보내지 않네요. size를 모르는데 전체 페이지 수를 어떻게 알까요? `requestDiaryByEmotion`랑 `requestDiaryNumByEmotion` 사이에 통일이 되어 있지 않다는 느낌을 받아요. 수정이 필요해보입니다!

2023-06-01 04:55 UTC, LAH1203 commented on src/constants/path.js
> +  DIARY_NUM_BY_EMOTION: '/dairy/emotion/num',
오타 있습니다! 저번 pr에서도 오타가 많았는데, 사소한 오타가 에러를 일으키는 경우가 많아서 조금 더 신경써주시면 좋을 것 같아요. (여기서도 이대로 두면 만약 서버와 연결했을 땐 통신이 안되는 에러가 발생하겠죠)

2023-06-01 04:55 UTC, LAH1203 commented on src/mocks/handlers/diary.js
> +};
이건 삼항연산자가 너무 많아서 오히려 가독성을 해치는 문제가 있는 것 같네요. `diaryLastCount`라는 이름도 뭘 의미하는지 명확하지 않아서 이게 뭔지 잠깐 생각했어요ㅠㅠ
일단 여기서 삼항연산자는 count가 10의 배수일 때는 나머지가 0이라 이를 10으로 하기 위해 쓰이죠? 그럼 이 판별 구문을 함수로 빼면 좀 더 가독성이 좋아질 것 같아요.

```js
const getLastPageCount = count => {
  return count % 10 > 0 ? count % 10 : 10;
};
```

그리고 `diaryLastCount`라는 변수를 굳이 만들 필요가 없을 것 같아요. 필요한 곳에서는 `getLastPageCount`를 쓰면 되니까요! 만약 `getLastPageCount`가 너무 자주 호출되면 문제겠지만, 지금으로서는 자주 호출될 여지가 없어보여요.

2023-06-01 04:55 UTC, LAH1203 commented on src/mocks/handlers/diary.js
> +    `${baseURL}${API_PATH.DIARY_BY_EMOTION}?mood=mood&page=page&size=10`,
msw에서 쿼리 스트링을 어떻게 사용하는지를 보신 것 같긴 한데, path에는 따로 붙이지 않습니다. 이럴 경우에는 mood가 mood고 page가 page고 size가 10인 경우에만 라우팅되거든요.

2023-06-01 04:55 UTC, LAH1203 commented on src/mocks/handlers/diary.js
> +              title: `${idx + 1}. 기분: ${mood}, 현 페이지 인덱스: ${page}`,
사실 사이트 보면서 이 타이틀이 계속 거슬렸는데, 실제로 api 응답 값은 이런 타이틀로 오지 않는 거겠죠? 그럼 여기도 임의로 제목을 붙여주시면 좋을 것 같아요. 피그마처럼 '롯데월드 갔다옴' 같은 것도 괜찮구요!

2023-06-01 04:55 UTC, LAH1203 commented on src/mocks/handlers/diary.js
> +              createAt: '2023.04.10',
createAt이 만들어진 날짜일텐데 백에서 api 응답 값으로 올 때도 이런 식으로 `년.월.일`로 처리해서 보내주기로 합의하신 게 맞나요? 만약 Date 형식으로 보내주시는 거면 프론트에서 가공하는 작업도 추가되어야 하고 msw도 수정되는 게 맞습니다. msw는 서버 합류 전 저희의 편의상 추가하는 것이기도 하지만 개발하면서 에러를 방지하는 용이기도 하거든요. 근데 msw는 이렇게 짰는데 만약 api는 Date 객체로 온다면 저희는 msw 기준으로 코드를 작성했으니 사용자한테 2023-04-10T23:59 같은 값을 보여주는 셈이 되겠죠?

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/FilterDiary/index.styles.jsx
> +`;
어차피 WrapperEmotion에서는 button을 스타일링 하는 거밖에 없는데 그냥 Button 컴포넌트를 만드는 게 낫지 않았을까요...

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/FilterDiary/index.styles.jsx
> +  }
scss 문법을 보셔도 좋을 것 같네요. 자식 요소에 접근하는 것에는 & 생략 가능합니다. 여기 말고도 자식 요소 접근에 거의 대부분 &를 쓰셨던데 수정하시면 좋을 것 같습니다. css in js가 편리하긴 하지만 문자열 형태로 들어가기 때문에 길이가 늘어나면 번들 크기가 커진다는 단점이 있거든요.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/List/Item/index.jsx
> +      )}
어차피 둘 중 하난데 삼항연산자가 좋아보입니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/List/Item/index.style.jsx
> +`;
음... 이미지 레퍼 스타일은 뭘 위해 존재하는 걸까요...? 어차피 자식 요소 img가 width, height 100%로 다 가려버리는데 🤣

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/List/index.styles.jsx
> +`;
어차피 grid 인 곳에만 스타일 적용하는데 그냥 className 쓰는 게 깔끔할 것 같아요

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/Pagination/index.jsx
> +  const [currentButtonIndex, setCurrentButtonIndex] = useState(0);
totalButtonIndex랑 currentButtonIndex가 무슨 역할을 하는 애들인지 감이 안 잡혀요.. 코드를 이해할 수가 없네요ㅠ

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/Pagination/index.jsx
> +      {console.log(mood, page)}
콘솔 로그 빼주세요

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/Post/Pagination/index.jsx
> +  const [currentButtonIndex, setCurrentButtonIndex] = useState(0);
이 컴포넌트 코드는 이해할 수가 없어서 리뷰 안하고 그냥 갈게요... 필요하시다면 리팩토링 하고 다시 요청해주세요...

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +    setParams(MOOD.BEST, 0);
쿼리 스트링 쓰셨던데 이러면 쿼리 스트링에 상관 없이 무조건 새로고침하거나 그 링크로 들어갈 때마다 best, 0번째 페이지에 바인딩됩니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +    setParams(MOOD.BEST, 0);
추가적으로 마이페이지에서 새로고침하면 무조건 t=info로 가던데 이러면 쿼리 스트링을 사용한 의미가 없습니다. 단순 상태를 이용한 것과 똑같은 상황입니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +  }, [searchParams.get('mood'), searchParams.get('page')]);
혹시 캐시 기능을 아십니까? 지금 경우에는 무조건 기분이나 페이지가 바뀔 때마다 요청하는데, 캐시 기능을 사용하면 이전의 요청했던 부분은 새로 요청하지 않고 캐시 데이터를 반환합니다. 만약 실시간성이 필요하지 않은 페이지라면 유효한 기능이죠. 얼마전에 제가 추가한 react-query에서 이 기능을 제공하니, 공부하고 적용해보시면 api 요청 최적화에 도움이 될 것 같습니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +    setParams(searchParams.get('mood'), 0);
기분이 바뀔 때 무조건 0번째 페이지로 요청하라고 의도하고 만드신 것 같아요. 근데 의도와는 다른 이런 에러가 발생합니다.

<img width="726" alt="image" src="https://github.com/2023-Capstone/capstone-front/assets/57928612/a41fadef-79b6-4443-9856-a49d64106269">
<img width="364" alt="image" src="https://github.com/2023-Capstone/capstone-front/assets/57928612/4eb4ad1e-b421-4b1b-826d-9ba42c4e1bc1">

다른 기분에서 8번째 페이지에 있다가 상 기분을 누르면 8번째 페이지를 먼저 요청하고 0번째 페이지를 요청하는데요. 실제로 보여지는 데이터는 8번째 페이지 부분이고 밑의 내비게이터는 0번째 페이지입니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +      size: LIMIT,
위의 리뷰로 size는 빼실 것 같긴 하지만, 이런 사용자가 알 필요 없는 size 같은 값은 굳이 searchParams에 넣지 않는 것이 좋습니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +  };
onThumbnail 함수는 이름만 봤을 때는 무슨 역할인지 정말 알기가 힘드네요.. 꾸준히 네이밍 관련해서 부족한 부분이 많이 보이는데 시간이 좀 더 걸리더라도 네이밍 부분을 신경 쓰면서 코딩하시는 연습이 필요할 것 같습니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +  };
이거는 그냥 컴포넌트로 빼고 다른 곳에서는 import로 불러와서 쓰는 것이 맞아보입니다.

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/Diary/index.jsx
> +    setParams(searchParams.get('mood'), 0);
추가적으로 이런 에러도 있습니다.

<img width="743" alt="image" src="https://github.com/2023-Capstone/capstone-front/assets/57928612/ed31bc31-b551-4543-8e7b-f0cc669cf59c">
<img width="366" alt="image" src="https://github.com/2023-Capstone/capstone-front/assets/57928612/83e06849-5cc4-4197-8214-7bec5fc55478">

2023-06-01 04:55 UTC, LAH1203 commented on src/pages/Mypage/index.styles.jsx
> +  }
자식 요소가 아닌 본인에게 거는 스타일에는 &를 붙여야 합니다. 자식에는 &를 붙이고 본인한테는 안 붙이셨네요ㅠ 실제 사용할 때는 정확히 반대입니다!

2023-06-23 01:22 UTC, LAH1203 approved these changes
어차피 나중에 리팩토링하신다고 해서 리팩토링 관련 부분은 안하고 머지되기 전 고쳐야하는 부분만 달았습니다. 간단한거니까 바로 approve 드릴테니, 고치고 머지해주세요.

2023-06-23 01:22 UTC, LAH1203 commented on src/hooks/useDidMount.js
> +const useDidMountEffect = (func, deps) => {
똑같은 동작하는 훅 이미 만든거 있습니다.

2023-06-23 01:22 UTC, LAH1203 commented on package.json
> +    "@tanstack/react-query-devtools": "^4.29.12",
devtools는 dependencies 보다는 devDependencies에 좀 더 맞을 것 같습니다

2023-06-23 03:01 UTC, Pridesd approved these changes
고생하셨습니당

2023-06-23 03:12 UTC, rewritestar commented
> 
말씀해주신 내용들 감사합니다! 아무래도 리액트 기본 지식 자체가 부족하다보니까, 리팩토링이나 네이밍 관련해서 눈에 안 들어오고 전체적인 감이 안 잡히는 것 같아요. 지금 당장 어떻게 고쳐야 하는지 몰라서 일단은 머지하지만, 추후에 습득한 지식으로 리팩토링이 가능한 점들이 보이면 수정해보도록 하겠습니다.

리뷰 덕분에 많이 배우고 있어요!! 감사합니다.

2023-06-23 03:16 UTC, merged