일기작성 페이지 에디터 외 기능 구현
2023-Capstone/capstone-front pull request #6
Opened 2023-04-09 13:08 UTC by Pridesd

욕해주세요 맘껏

2023-04-10 04:17 UTC, LAH1203 requested changes
일단은 코드랑 실행하면서 발견한 부분만 코멘트 남겼습니다! 천천히 생각해보시고 답 남겨주세요 :)

2023-04-10 04:17 UTC, LAH1203 commented on src/App.jsx
> +              <Route path={BROWSER_PATH.EDITOR} element={<Editor />} />
Editor → Edit으로 전부 변경해주세요! (BROWSER_PATH, 컴포넌트 이름 모두 포함)
저 이름은 path랑 통일이라서요. path가 edit이니 통일해주세용

2023-04-10 04:17 UTC, LAH1203 commented on src/apis/request/weather.js
> +  }
음 에러를 catch 했을 때 정말 console.error만 하고 넘기는 게 맞을까요? 사용자가 이 사이트를 사용할 때 콘솔창을 켜서 볼까요? 웬만해선 아닐거라고 생각해요. 그럼 무슨 처리를 하는 게 좋을까요?

2023-04-10 04:17 UTC, LAH1203 commented on src/constants/message.js
> +    REPUTATION_HASHTAG: '이미 존재하는 해시태그입니다',
통일해서 메시지 끝에 `.`을 찍어볼까요!

그리고 '이미 존재하는 해시태그'라는 에러 메시지의 키가 `REPUTATION_HASHTAG`인 게 맞을까요? reputation이 낯설어서 번역 돌려보니 평판이란 뜻이더라고요. 키는 키만 보고도 무슨 에러인지 바로 알 수 있을만큼 명확한 게 좋다고 생각해요. 여기선 중요한 키워드가 '중복'이니, `DUPLICATED_HASHTAG` 정도가 어떠신가요? 🙂

2023-04-10 04:17 UTC, LAH1203 commented on src/constants/path.js
> +  EDITOR: '/edit',
여기도 위에서 말씀드린 EDITOR → EDIT 변경입니다

2023-04-10 04:17 UTC, LAH1203 commented on src/hooks/useCheckBlank.js
> +};
내용을 보면 단순 validate라 유틸 함수로 빠져도 될 것 같은데, 훅으로 빼신 이유가 있나요?

추가적으로 단순히 text의 길이가 0인 걸 판단하는 함수 이름이 isNull인 건 맞지 않은 것 같아요. 빈 문자열과 null은 엄연히 다르니까요. 빈 문자열을 판단하는 함수라는 의미의 네이밍으로 바꾸는 게 좋을 것 같습니다.

2023-04-10 04:17 UTC, LAH1203 commented on src/hooks/useWeather.js
> +  const weather = useRef('');
ref 보고 음...? 했어요. 파악한 바로는, 현재 날씨 문자열만 저장하는 거 아닌가요? 그러면 그냥 useState를 사용해도 될 것 같은데, ref를 사용하신 건 비제어로 만들고 싶어서 하신걸까요? 만약에 그러신 거라면 이유가 궁금해요! 리액트는 공식에서도 설명하지만, 리렌더링이 자주 일어나지 않는 이상 저희가 신경 쓸만큼 큰 부하가 있는 게 아니거든요,,

2023-04-10 04:17 UTC, LAH1203 commented on src/hooks/useWeather.js
> +  const failedGetLocation = () => {
함수명은 관습 상 동사로 하는 게 낫습니다. 위에서도 알맞게 success를 써주셨으니 여기도 fail로 써볼까요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/EditorBox/index.jsx
> +    </S.Container>
여기는 아직 하지 않은 부분이니 style 파일이랑 같이 언급하지 않고 넘어갈게용,,

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +  return (
여기도 그렇고 다른 파일들도 그렇고 조금 보기 힘든데, 함수랑 리턴문 사이에는 엔터 하나씩 추가 가능할까요? ㅠㅠㅠ

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
newHashtag 부분은 제가 만든 useInput 훅을 사용해주세요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +    }
if 문 안의 내용이 길어지면 결국 한 뎁스 더 있는 구문이 길어져서 보기가 조금 힘들어요. 그래서 클린코드 관점에서도 예외처리를 먼저 하라는 게 있는 것 같아요,,
이 부분에서는 key가 'Enter'가 아닐 땐 아무것도 하지 않으니 그럴 때를 먼저 예외처리 해주면 훨씬 나아져요.

```suggestion
    if (key !== 'Enter') return;

    if (isBlank(newHashtag) || isNull(newHashtag)) {
      showSnackbar(CLIENT_MESSAGE.ERROR.EMPTY_HASHTAG);
      setNewHashtag('');
      
      return;
    }
    if (hashtagList.length === 5) {
    showSnackbar(CLIENT_MESSAGE.ERROR.FULL_HASHTAG_LIST);
      setNewHashtag('');
      
      return;
    }
    if (hashtagList.includes(newHashtag)) {
    showSnackbar(CLIENT_MESSAGE.ERROR.REPUTATION_HASHTAG);
      setNewHashtag('');
      
      return;
    }
    setHashtagList(prev => [...prev, newHashtag]);
    setNewHashtag('');
```

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +      if (hashtagList.length === 5) {
해시태그 수의 최대값인 5는 매직 넘버이니, constants로 분리해서 사용하는 게 좋아요. 제가 constants 폴더에 rule.js 파일을 만들어놨는데 여기에 추가해서 가져와 사용하는 방식으로 바꿔보시는 건 어떨까요?

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +    }
그리고 이건 UX와 관련된 것이긴 한데요. 사용자가 잘못 입력해서 무언가 제출하는 트리거를 했을 때, (저희의 경우는 엔터겠죠?) 내가 뭘 입력해서 잘못한건지 기억나지도 않는데 개발자가 잘못 입력한 경우는 무조건 입력한 값을 초기화하도록 만들어서 매우 불편하다는 게 요즘 종종 등장하는 피드백입니다. 그래서 요즘은 잘못 입력해도 input을 잘 비워주지 않습니다. 여기도 마찬가지로 비워주지 않는 방식으로 가면 좋을 것 같아요. 비워주는 건 제대로 입력해서 추가됐을 때에 한해서!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
이미 상태로 받는 hashtagList가 있는데 굳이 prev를 받을 필요는 없겠죠..?

그리고 다른 곳은 hashtag로 사용해주셨는데 여긴 hashTag네요! T는 소문자로 바꿔봐요,,

```suggestion
  const deleteHashtag = name => {
    setHashtagList(hashtagList.filter(hashtag => hashtag !== name));
  };
```

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +          <S.Hashtag onClick={() => deleteHashTag(hashtag)} key={index}>
익명함수는 좋지 않아요! deleteHashtag를 커링 함수로 만드는 것을 추천합니다.

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +          <S.Hashtag onClick={() => deleteHashTag(hashtag)} key={index}>
그리고 key 값이 index인 것은 안티패턴입니다. 안티패턴이 아닌 경우도 있는데, 그것은 배열 순서가 바뀌지 않는 경우이고요. 근데 여기서는 배열 순서가 지속적으로 바뀌죠. (삭제가 가능하니까요!) 그래서 key 값으로 index를 사용하면 안돼요.
해시태그는 중복 불가이니 해시태그 자체를 키 값으로 줘도 될 것 같네요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +    }
추가적으로 에러 발견했습니다. 해시태그가 한글일 때는 추가하면 `해시태그 값을 입력해주세요` 에러가 발생하네요.

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +const TitleInput = ({ title, setTitle, date, weather, mood, setMood }) => {
음 Input만 있는 게 아닌데 컴포넌트 이름이 TitleInput이 맞을까요?

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +      );
이건 저도 리액트를 처음 할 때 했던 실수여서 꼭 말씀드리고 싶었습니다. 단순히 set을 하는 건 보통 함수로 사용하지 않습니다. (상태 업데이트가 비동기라서 최신화의 prevState가 꼭 필요할 때만 사용)
그리고 날짜 변환 자체가 상태로 저장되어 있는 것은 좋지 않다고 생각해요. 가능한 한 상태는 사용자 상호작용으로 변할 가능성이 있는 것만 빼야 합니다. 그래서 저는 이 문장 자체는 리턴 문 안에 있어야 한다고 생각해요.

```jsx
<p>date: `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()} (${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].at(date.getDay())})`</p>
```

그리고 요일에 따라 Sun, Mon 등으로 변환하는 것은 가독성 좋게 유틸 함수로 빼는 편이 좋겠네요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +    }
여기도 위와 마찬가지로 weather을 아이콘으로 변환하는 부분은 상태로 관리할 필요가 없어요. 이미 존재하는 상태를 가공한 상태이니까요. 상태를 늘리는 건 좋지 않아요.

그럼 위 useEffect와 이 useEffect가 모두 사라지겠네요.

```jsx
<p>weather: {weather ? weatherToIcon(weather) : '업데이트 중'}</p>
```

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +      </S.DateBox>
이 부분 정렬이 피그마랑 다르네요. 조금 힌트를 드리자면 grid를 사용해보시면 좋을 것 같아요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +          </select>
select 부분도 피그마처럼 스타일해주세요! 선 색 변경하고, 포커스 됐을 때 선도 없애주시면 될 것 같아요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +import React, { useEffect, useState } from 'react';
이제 `import React from 'react';`는 필요 없는 구문입니다! 삭제해주세요 :)

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +      {/* //에디터 박스 윗부분 */}
개발 끝나신 부분의 주석은 삭제해주세요 ㅎㅎ

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +const Editor = () => {
여기 이름도 Editor → Edit으로 변경해주세요!

2023-04-10 04:17 UTC, LAH1203 commented on src/hooks/useWeather.js
> +export { useWeather };
여기 export default가 안됐어요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  }, []);
useEffect가 많은 것도 좋은 코드는 아니라고 합니다. 이런 초기값 지정은 useState로 정의하는 단에서 지정해주세요!

```js
const [date, setDate] = useState(new Date());
```

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  }, [getWeather]);
useEffect는 useEffect끼리 모아놓는 게 좋아요! 따지고보면 분기라서 useEffect에서 에러가 나는 경우가 많은데, 그럴 때 모아보면 훨씬 낫습니다. 그래서 저는 개인적으로 상태, 훅, useEffect, 함수, 리턴문 순으로 정렬해요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  };
이것도 제가 만들었던 useInput 훅을 사용해주세요 :)

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  };
함수 네이밍은 변경해야겠네요..! '어떤 동작에 대한 핸들러'라는 의미보다는 이 함수가 무슨 동작을 하는지에 포커스를 맞춰 네이밍을 하는 게 좋아요.

예를 들면 취소 버튼을 눌렀을 때는 /가 아닌 이전 페이지로 가야겠죠? 그러면 이런 식으로 되겠네요.

```jsx
const goToPrevPage = () => {
  navigate(-1);
};

return (
  <button onClick={goToPrevPage}>취소</button>
);
```

등록도 마찬가지입니다. 새로운 일기의 등록이니 그에 맞는 네이밍으로 변경하는 것이 좋아요.

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +        setHashtagList={setHashtagList}
사실 이렇게 setter를 바로 넘기는 것은 안전하지 않아 좋지 않다고 합니다! 개인적으로는 addHashtag와 removeHashtag 함수를 만들어 props로 전달하는 방식을 추천해요 :)

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +        showSnackbar={showSnackbar}
showSnackbar는 커스텀 훅이니 아무곳에서나 불러서 쓸 수 있어요! 커스텀 훅으로 분리한 것들은 props로 따로 전달하지 않고 사용하는 곳에서 커스텀 훅으로 가져와서 사용해요.

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.styles.jsx
> +  button:first-child {
여기 콘솔에서 이런 에러가 납니다!

```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```

잘 해결하실 수 있을거라 믿어요 호호

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.styles.jsx
> +  }
버튼 크기와 글씨 크기가 너무 커요! 조정이 필요해 보입니다 ㅠㅠ

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +export default Editor;
모바일 버전도 만들어주셔야 할 것 같아요~ 모바일 버전이 따로 없네요!

2023-04-10 04:17 UTC, LAH1203 commented on src/pages/Edit/index.styles.jsx
> +    color: #ffffff;
`white` vs `#ffffff ` vs `#fff`

2023-04-10 04:17 UTC, LAH1203 commented on src/utils/weatherToIcon.js
> +      return <TbViewfinderOff />;
개인적으로는 여기 default 아이콘을 로딩 관련 아이콘으로 바꿔서 title의 weather 부분을 `<p>weather: {weatherToIcon(weather)}</p>`로 바꾸는 걸 추천드려요! '업데이트 중'이라는 문구가 너무 길어서 날씨를 불러왔을 때 바뀌는 게 레이아웃이랑 아이콘 바뀌는 게 너무 눈에 띄더라고요ㅠㅠ

2023-04-10 04:20 UTC, Pridesd commented on src/constants/message.js
> +    REPUTATION_HASHTAG: '이미 존재하는 해시태그입니다',
아 duplicated ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 뭔 생각으로 reputation이라고 적은건지 ㅋㅋㅋㅋㅋ

2023-04-10 04:22 UTC, Pridesd commented on src/hooks/useCheckBlank.js
> +};
아 생각해보니까 validate가 맞겠네요 그냥 훅 한 번 만들어보자는 생각에 해봤습니다,,

2023-04-10 04:23 UTC, Pridesd commented on src/pages/Edit/index.styles.jsx
> +  button:first-child {
아악 이 에러가 왜 나는지 했는데 이거 때문이었네여 알겠습니다!!

2023-04-10 04:25 UTC, Pridesd commented on src/App.jsx
> +              <Route path={BROWSER_PATH.EDITOR} element={<Editor />} />
앗 네넵!
옛날 흔적을 지우는 걸 깜빡했네요!!

2023-04-10 04:27 UTC, Pridesd commented on src/apis/request/weather.js
> +  }
alert처리를 하고 이전 페이지로 돌아가야겠네요../

2023-04-10 04:29 UTC, Pridesd commented on src/pages/Edit/index.styles.jsx
> +    color: #ffffff;
정답 white

2023-04-10 04:29 UTC, Pridesd commented on src/pages/Edit/index.styles.jsx
> +  }
저는 괜찮다고 생각했는데 0.25 rem씩 줄여볼게요!

2023-04-10 04:30 UTC, Pridesd commented on src/utils/weatherToIcon.js
> +      return <TbViewfinderOff />;
아 네 알겠습니다!!

2023-04-10 04:33 UTC, Pridesd commented on src/hooks/useWeather.js
> +  const weather = useRef('');
맨처음에 useState를 사용했었을때 자꾸 정보 업데이트가 늦더라고요 ㅜㅜ 
그래서 찾아보니까 useRef를 사용했을 떄 비동기적으로 작동하는 set함수랑은 다르게 useRef는 즉각적으로 변경할 수 있다고 햬서 useRef를 사용한겁니다!

2023-04-10 04:33 UTC, Pridesd commented on src/hooks/useWeather.js
> +  const failedGetLocation = () => {
넵넵

2023-04-10 04:34 UTC, Pridesd commented on src/pages/Edit/EditorBox/index.jsx
> +    </S.Container>
넵,, 여기는 아예 안 건들었어용,,

2023-04-10 04:34 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +  return (
아 알겠습니다!!

2023-04-10 04:35 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
오 그거는 확인 못했었네요 useInput 사용법 확인해보고 사용하겠습니당

2023-04-10 04:37 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +    }
key가 enter가 아닐 때 예외처리 먼저,
잘못된 해시태그를 입력할 땐 input 그대로 두기
한글 입력 에러 해결
확인했습니다!

2023-04-10 04:38 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +      if (hashtagList.length === 5) {
해시태그 수 최댓값 contant로 분리하기!

2023-04-10 04:40 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
이미 상태로 받는 hashtagList가 있는데 굳이 prev를 받을 필요는 없겠죠..? -> 그래도 set을 쓸 때는 prev를 통해 수정하는 게 안정성 측면에서 더 낫지 않나요?? 

다른 곳은 hashtag로 사용해주셨는데 여긴 hashTag네요 -> 어머 이건 미스테이크

2023-04-10 04:43 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +          <S.Hashtag onClick={() => deleteHashTag(hashtag)} key={index}>
deleteHashtag를 커링 함수로 만드는 것을 추천합니다. -> 커링함수!! 찾아보고 적용해볼게요
 해시태그 자체를 키 값으로 줘도 될 것 같네요 -> 아 처음에 중복이 상관없었을 떄 적용한 거였는데 생각해보니 이젠 key값을 해시태그 이름으로 해도 되겠네요 감사합니다!!

2023-04-10 04:43 UTC, Pridesd commented on src/pages/Edit/TitleInput/index.jsx
> +const TitleInput = ({ title, setTitle, date, weather, mood, setMood }) => {
Title...Info..?

2023-04-10 04:45 UTC, Pridesd commented on src/pages/Edit/TitleInput/index.jsx
> +      );
헉 감사합니다!!

2023-04-10 04:46 UTC, Pridesd commented on src/pages/Edit/TitleInput/index.jsx
> +    }
오.. 알겠습니다 아래 거랑 같이 적용해서 해볼게요!

2023-04-10 04:46 UTC, Pridesd commented on src/pages/Edit/TitleInput/index.jsx
> +      </S.DateBox>
그리드!! 써볼게요..

2023-04-10 04:47 UTC, Pridesd commented on src/pages/Edit/TitleInput/index.jsx
> +          </select>
넵!!

2023-04-10 04:47 UTC, Pridesd commented on src/hooks/useWeather.js
> +export { useWeather };
앗 네넵!!

2023-04-10 04:47 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  }, []);
헉 알겠습니다!!

2023-04-10 04:48 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  }, [getWeather]);
그냥 하나의 useEffect로 관리하는게 낫다는 말씀이시죠?

2023-04-10 04:48 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  }, [getWeather]);
아 아니네요 알겠습니다!!!

2023-04-10 04:48 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  };
넵...!!

2023-04-10 04:49 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  };
넵....ㅜ

2023-04-10 04:49 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +        setHashtagList={setHashtagList}
앗 다른 것들은 그렇게 했는데 이건 그렇게 안해놨네요 알겠습니다!!

2023-04-10 04:50 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +        showSnackbar={showSnackbar}
넵...!!!!

2023-04-10 04:51 UTC, rewritestar commented
피드백 제가 받고 갑니다...

2023-04-10 05:05 UTC, LAH1203 commented on src/apis/request/weather.js
> +  }
네! 근데 request 함수 내에서 있는 것은 함수 관심사 분리에 어긋나니 올바르지 않고, 여기선 단순히 error를 throw 해서 이 request 함수를 사용하는 컴포넌트 또는 훅에서 catch 해서 적용하시는 게 좋을 것 같아요~

2023-04-10 05:07 UTC, LAH1203 commented on src/hooks/useWeather.js
> +  const weather = useRef('');
오호 가시적으로 차이가 많이 났나요?

2023-04-10 05:11 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
만약 setter가 너무 느려서 해시태그를 삭제하는 속도가 추가되는 속도보다 빠르면 최신화가 필요할 수 있지만, 저희의 경우에는 이미 추가되어 보여지는 해시태그만 클릭하여 삭제할 수 있으니 여기에서는 불필요한 부분이라고 생각해요!

2023-04-10 05:12 UTC, LAH1203 commented on src/pages/Edit/TitleInput/index.jsx
> +const TitleInput = ({ title, setTitle, date, weather, mood, setMood }) => {
저는 네이밍을 잘 못하긴 하는데,, 그냥 생각나는건 단순히 Title로도 괜찮지 않을까 생각합니다 ㅎ.ㅎ

2023-04-10 05:16 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  };
제가 말투가 너무 딱딱하죠…? ㅠㅠ 글로 쓰면 이렇더라고요,,, 화내는건 아니었습니다 🥲

2023-04-10 05:18 UTC, LAH1203 commented on src/pages/Edit/index.styles.jsx
> +    color: #ffffff;
절반만 정답이니 50점 드리겠습니다~

귀찮으면 white, 글자수 줄이기는(용량 + 시간) #fff입니당 ㅎㅎㅎ

2023-04-10 05:25 UTC, Pridesd commented on src/hooks/useWeather.js
> +  const weather = useRef('');
네네 제가 봤었을땐 많이 차이났어요 ㅠㅠ

2023-04-10 05:25 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +  };
알겠습니다!!

2023-04-10 05:26 UTC, Pridesd commented on src/pages/Edit/index.jsx
> +  };
아 ㅋㅋㅋㅋㅋ 아닙니다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-04-10 05:26 UTC, Pridesd commented on src/pages/Edit/index.styles.jsx
> +    color: #ffffff;
아하,, 알겠습니다!!

2023-04-10 12:39 UTC, Pridesd commented on src/hooks/useWeather.js
> +  const weather = useRef('');
그냥 useState로 수정했스니다!

2023-04-10 13:51 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.jsx
> +          <S.Hashtag onClick={() => deleteHashTag(hashtag)} key={index}>
커링함수를 도통 모르겄네요

2023-04-14 04:19 UTC, LAH1203 requested changes
수정하고 추가하신 부분 대략적으로 확인했습니다~

근데 전에 확인했던 해시태그로 한글 입력 시 스낵바가 뜨는 건 계속 그러네요ㅠㅠ 이건 해결해주셔야 할 것 같아요.

저번에 잘 믿지 못하시는 것 같아서 이번에 영상으로 찍어왔어요 ㅎㅎ..

https://user-images.githubusercontent.com/57928612/231938498-e9447ae8-ecee-4037-af5a-2019a5343b9c.mov

추가적으로, 5개일 때 한글 입력해도 이런 식으로 5개 메시지가 씹혀요.


https://user-images.githubusercontent.com/57928612/231939757-e2856ff7-e326-4727-994d-fb93228560c7.mov

2023-04-14 04:19 UTC, LAH1203 commented on src/constants/rule.js
> +  HASHTAGLIST: {
hashtag list는 한 단어가 아니니 중간에 `_`를 넣어주시면 좋겠네요!

2023-04-14 04:19 UTC, LAH1203 commented on src/hooks/useWeather.js
>    return { getWeather };
이제보니 weather은 클래스의 private 같은 속성이 아닌데 getter가 있었네요! 단순히 날짜 반환만 하는 것이라면 그냥 getWeather라는 함수 없이 `return { weather }`만 해도 될 것 같습니다~

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/Title/index.jsx
>    const [transDate, setTransDate] = useState('');
전에 제 리뷰는 transDate라는 이미 가지고 있는 date란 값에 대한 형태 변환은 상태로 가지고 있을 필요는 없을 것 같다는 것이었는데, 혹시 이 상태는 유지하신 이유가 있나요?

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +  const [newHashtag, onChangeNewHashtag, resetNewHashtag] = useInput('');
newHashtag란 상태는 해시태그 박스 의존적이니 이전처럼 해시태그 박스에 두고 사용하는 게 좋을 것 같아요. addHashtagItem에 필요하다면 인자로 newHashtag 값을 받으면 되니까요! 부모 컴포넌트에서 자식 컴포넌트의 상태가 꼭 필요하지 않은데 모두 가지고 있는 것도 바람직한 방법은 아니라고 생각해요.

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/index.jsx
> +    setHashtagList(hashtagList.filter(hash => hash !== name));
만약에 사용자가 돔을 조작하여 name으로 이상한 값이 들어가면 어떻게 될까요? 안전하게 하려면 그에 대한 예외처리도 필요할 것 같네요~

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/Title/index.jsx
> +            <label htmlFor="mood">mood </label>
mood 뒤에 스페이스가 들어가있네요

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/Title/index.jsx
> +        </S.DateInfo>
여기 부분이 모바일 기준보다 살짝 클 때 이런 식으로 보여요

![image](https://user-images.githubusercontent.com/57928612/231936474-de96d457-39f6-4cfd-8245-4e302d7f8062.png)

이 컴포넌트는 아니지만, Edit 페이지 padding 조정을 해야할 것 같다고 생각됩니다.

2023-04-14 04:19 UTC, LAH1203 commented on src/utils/weather.js
> +          width="20"
보니까 svg의 크기는 1em으로 주셨던데 로딩바의 크기는 20px이니 svg의 크기가 유동적으로 변할 때 로딩바의 크기는 계속 20px 고정이라 레이아웃이 계속 유동적으로 바뀝니다. 크기 통합이 필요해 보이네요. 다만 px 고정은 rem 단위가 바뀌더라도 계속 고정이니, 글씨랑 같은 줄에서 보이기 위해선 px은 자제해야겠죠..?

2023-04-14 04:19 UTC, LAH1203 commented on src/utils/weather.js
>            wrapperStyle={{}}
사용하지 않는 부분은 지워주세요 🙂

2023-04-14 04:19 UTC, LAH1203 commented on src/utils/weather.js
> +const getDay = day => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].at(day);
weather이라는 파일 안에 요일을 반환하는 함수가 있는 게 맞을까요? 🤔

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +            <label htmlFor="hashtag">
참고로, 요즘 label과 input을 연결할 때는 id와 htmlFor를 사용하지 않고 label 안에 input을 넣습니다 ㅎㅎ

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +              #{hashtag}
여기에 남길 것은 아니지만, 기억이 안나서 여기에 남겨요~
제목 input의 글씨 크기는 작은 것에 비해 (해시태그 input과 동일) 남겨지는 해시태그 글씨 크기는 너무 크더라고요. 제목 input은 조금만 키우고 해시태그 (input 아님) 글씨 크기는 조금 줄이면 좋을 것 같아요.

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
>      <>
최상단이 Container로 하나면 빈 태그는 사용하지 말아주세요. 빈 태그는 반환하려는 여러 엘리먼트를 하나로 묶을 때만 사용해야 해요. 다른 파일도 이런지는 확인을 못해봤는데, 혹시 그렇다면 없애주세요 ㅠㅠ

2023-04-14 04:19 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.styles.jsx
>    align-items: center;
해시태그 리스트가 길어지면 가운데 정렬 때문에 input이 자꾸 밑으로 내려가요.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/57928612/231940259-17a59a8e-aa51-499d-9aca-c46d64b8c0b5.png">

2023-04-14 04:19 UTC, LAH1203 commented on src/styles/theme.js
> +};
theme에 이미 breakpoints가 있는데 screenSize로 가공해서 theme에 또 정의해주신 이유가 있나요? 만약에 min-width랑 max-width를 모두 지정하는 경우에는 사용하지 못할 것으로 보여서요.

2023-04-14 04:30 UTC, Pridesd commented on src/styles/theme.js
> +};
아 이거는 max-width 자꾸 치기 귀찮아서 이렇게 만들었는데 그냥 없애요..?

2023-04-14 06:32 UTC, Pridesd commented on src/pages/Edit/Title/index.jsx
>    const [transDate, setTransDate] = useState('');
실수였슴당 ㅎ

2023-04-14 09:33 UTC, LAH1203 commented
해시태그 박스... 해시태그 input이랑 해시태그 리스트가 붙었어요 ㅠ

<img width="636" alt="image" src="https://user-images.githubusercontent.com/57928612/232006317-f3009b8e-0153-42f6-b474-68e33df7fc76.png">

그리고 해시태그 input 글씨 크기가 제목이랑 같이 커졌어요..! 리뷰 적을 때 제목만이라고 적었었는데, 고치시면서 헷갈리신 것 같아요 ! 해시태그 input은 글씨 크기를 별도로 줄여주시면 좋을 것 같아요 🥲

2023-04-14 09:45 UTC, LAH1203 reviewed
.

2023-04-14 09:45 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.styles.jsx
> +    color: black;
기본 컬러가 black이라 빼셔도 되겠네요

2023-04-14 09:45 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.styles.jsx
>    input {
참고로,, 이런 식으로 컴포넌트 내에서 엘리먼트 자체에 접근하여 스타일을 주는 방식이 권장하는 방식은 아닙니다. 코드를 파악하기 힘들고 추후에 오류도 많이 생기니까요. 처음엔 그냥 넘어갔는데 이런 코드가 점점 늘어나서 남겨요ㅠ 조금만 자제해주세요...

2023-04-14 09:45 UTC, LAH1203 commented on src/pages/Edit/index.jsx
>      setHashtagList(hashtagList.filter(hash => hash !== name));
(사실 hashtagList 자체의 길이가 5밖에 안돼서 여기엔 해당하는 내용이 아니니 고치실 필요는 없고, 그냥 남기는 코멘트이니 참고만 해주세요.)

includes랑 filter 모두 자바스크립트 array 메서드인 건 아실거라고 생각해요. 근데 두 메서드 모두 배열 전체를 훑고 가고, 현재 같은 상황에선 name과 같은 요소를 찾는 것이니 비슷한 동작을 하고 있어요. 이런 경우 2번은 도는 것은 낭비죠. 그래서 `findIndex` 같은 메서드를 사용하여 한 번만 돌고, 이에 대한 예외처리를 하는 편이 훨씬 나아요. 만약 회원 배열에서 내가 원하는 회원을 찾는데 회원 배열의 길이가 1000만이라면? includes로 포함되어 있는지 전부 확인하고 filter로 그 사람을 한 번 더 찾아내서 그 사람을 제외한 새로운 배열을 만들고, 이 과정 자체가 최악의 경우 1000만 번 걸릴 일을 2000만 번으로 늘리는 셈이 되죠. 사실 그래서 배열 메서드를 사용할 때는 중복 로직을 제거하는 게 중요해요. 이 부분은 인식하고 계시면 나중에도 도움이 될 것 같아서 참고로 남겨봅니다 🙂

2023-04-14 09:45 UTC, LAH1203 commented on src/styles/theme.js
> +// };
주석 👋

2023-04-14 09:50 UTC, LAH1203 commented on src/pages/Edit/HashtagBox/index.jsx
> +    if (isBlank(newHashtag) || checkLength(newHashtag)) {
보니까 isBlank에서 하는 일이 checkLength를 확인하는 일이더라고요. isBlank만 사용해도 될 것 같습니다.

2023-04-14 10:55 UTC, Pridesd commented on src/pages/Edit/HashtagBox/index.styles.jsx
> +    color: black;
아 이건 위에 label을 초록으로 지정해서 다시 색 바꾸는 겁니다 ㅜ

2023-04-14 10:56 UTC, Pridesd commented on src/pages/Edit/index.jsx
>      setHashtagList(hashtagList.filter(hash => hash !== name));
넵..! 지금 수정할게요!!

2023-04-14 11:26 UTC, merged