마이페이지: 프로필 수정 페이지 개발
2023-Capstone/capstone-front pull request #7
Opened 2023-05-07 09:42 UTC by rewritestar

### 데모 페이지
https://develop--taupe-pavlova-b8322c.netlify.app/

**프로필 수정 페이지 구현**

- 닉네임 및 이메일 수정
- 회원탈퇴 모달 페이지 추가 및 회원 탈퇴 기능

*모바일 버전X, 추후에 구현 예정

2023-05-07 10:06 UTC, Pridesd reviewed
저는 로직은 잘 모르겠구,, 이름 수정했으면 하는 부분 적어놨습니다..!

2023-05-07 10:06 UTC, Pridesd commented on src/constants/message.js
> +    FAIL_NICKNAMEUPDATE: '닉네임 수정에 실패하였습니다.',
개인적으로 FAIL_NICKNAME_UPDATE가 맞을 것 같습니다! 위에 이메일도요!

2023-05-07 10:06 UTC, Pridesd commented on src/pages/Mypage/MyInfo/Inputs/Button/index.jsx
> +      <S.Button onClick={onClick}>수정</S.Button>
여기에 단순히 수정보다는 이메일 수정, 닉네임 수정 같이 어떤 걸 수정하는 지 값을 props로 받아서 했으면 좋겠습니당

2023-05-07 10:06 UTC, Pridesd commented on src/pages/Mypage/MyInfo/Inputs/index.jsx
> +          이메일 형식이 올바르지 않아요.
개인적인 생각으론 유효한 값일 때 색이 회색으로 되는 게 아니라 display none이 되면 더 좋지 않을까 생각해봅니당

2023-05-07 10:06 UTC, Pridesd commented on src/pages/Mypage/MyInfo/index.jsx
> +  const [nickname, changeNickname] = useInput('');
changeNickname보다 원래 이름 그대로 onChangeNickname이 더 좋지 않을까 싶습니다!

2023-05-07 10:06 UTC, Pridesd commented on src/pages/Mypage/MyInfo/index.jsx
> +      <WithdrawlModal onWithdrawl={handleWithdrawl} />
Withdrawl이 아니라 Withdrawal입니당..ㅎㅎ

2023-05-07 11:46 UTC, rewritestar commented on src/constants/message.js
> +    FAIL_NICKNAMEUPDATE: '닉네임 수정에 실패하였습니다.',
이거는 참고해서 바꿔볼게요!

2023-05-07 11:47 UTC, rewritestar commented on src/pages/Mypage/MyInfo/Inputs/Button/index.jsx
> +      <S.Button onClick={onClick}>수정</S.Button>
피그마에 그린대로 구현한 것인데, 어떻게 할까요?

2023-05-07 11:48 UTC, rewritestar commented on src/pages/Mypage/MyInfo/Inputs/index.jsx
> +          이메일 형식이 올바르지 않아요.
이 부분은 아현님이 구현하신 회원가입 폼을 그대로 가져다 쓴거라 통일하는 것이 좋을 것 같은데, 저는 개인적으로 회색이 좋아보였습니다!

2023-05-07 13:56 UTC, LAH1203 requested changes

2023-05-07 13:56 UTC, LAH1203 commented on src/App.jsx
> +import DiariesByEmotion from './pages/Mypage/DiariesByEmotion';
여기 포함해서 다른 파일들 import 절대경로가 안되어있던데, 이 부분 확인하고 수정해주세요.

2023-05-07 13:56 UTC, LAH1203 commented on src/App.jsx
> +                ></Route>
컴포넌트 안에 자식 요소나 텍스트가 없다면 따로 닫힘 태그를 두지 않고 하나로 작성하는 게 관습입니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/apis/request/auth.js
> +};
이메일, 닉네임 수정과 회원탈퇴를 왜 리프레시 토큰으로 요청하나요? ㅠ
리프레시 토큰과 액세스 토큰은 서로 다릅니다. 만약 API 문서 작성 시에도 리프레시 토큰으로 요청하는 것으로 했다면, 액세스 토큰으로 바꾸는 게 맞습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/apis/request/auth.js
> +};
추가적으로 재석님이 남겨주시기도 했지만 withdrawal로 고쳐주셔야 할 것 같습니다. 전체적으로 이렇게 사용하신 것 같더라고요.

2023-05-07 13:56 UTC, LAH1203 commented on src/apis/request/auth.js
> +const requestEmailUpdate = userData => {
`requestEmailUpdate`와 `requestNicknameUpdate` 모두 보면 Update가 뒤로 가있는데, 보통 함수명을 지을 땐 동사 형태가 앞으로 나옵니다. 그래서 `requestUpdateEmail`과 `requestUpdateNickname`으로 쓰는 것이 좋을 것 같습니다. 그냥 넘어가려다가 신경이 쓰여서 남겨봅니다,,

2023-05-07 13:56 UTC, LAH1203 commented on src/constants/message.js
> +    FAIL_NICKNAMEUPDATE: '닉네임 수정에 실패하였습니다.',
success 부분도 당연히 같이 수정하시겠죠? withdrawal 오타 하나 더 있습니다ㅎㅎ

2023-05-07 13:56 UTC, LAH1203 commented on src/constants/path.js
> +  },
url이 이렇게 나뉘어서 pathname으로 들어가는 게 맞을까요?
네이버의 마이페이지를 참고하셨다고 하셨는데, 네이버 마이페이지 각 탭의 pathname은 바뀌지 않습니다. `https://nid.naver.com/user2/help/myInfoV2?m=viewSecurity`와 `https://nid.naver.com/user2/help/myInfoV2?m=viewManageHistory` 같이 myInfoV2의 path는 유지하고 뒤 쿼리스트링의 m만 바뀌죠. 그래서 지금으로썬 어느 부분을 참고하신 건지 의문이 듭니다ㅠㅠ

2023-05-07 13:56 UTC, LAH1203 commented on src/constants/path.js
> +  },
그리고 이대로 한다고 하셔도 또 하나의 이상한 부분이 있습니다. myinfo는 그렇다쳐도 diariesbyemotion는 너무 길지 않나요? url에서 구구절절히 이 페이지에선 어떤 기능을 한다고 설명할 필요는 없습니다. 이건 무슨 페이지다라고 대략적으로 나타낼 수 있는 짧은 단어 하나나 두 개정도가 적당하죠. 그리고 복수형도 잘 사용하지 않습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/constants/path.js
> +  },
(도움이 될까 싶어서 제 생각을 남겨봅니다만, 어디까지나 참고용으로만 봐주세요.)

### Case 1. 지금처럼 pathname을 사용하는 경우

이 경우, 저는 이렇게 바꿀 것 같습니다.

```js
MYPAGE: {
  BASE: '/me',
  INFO: '/info',
  DIARY: '/diary',
},
```

우선 베이스 pathname이라는 표시를 줍니다. 사실 mypage라는 pathname은 너무 길어서 me를 애용합니다. 그리고 당연히 이미 마이페이지인데 여기에서 다른 사용자의 정보를 보는 것은 아니겠죠. 때문에 myinfo에서 my는 제거합니다. 또, 마이페이지에서 기분별 일기를 모아보는 것은 맞으나 그 외의 필터된 일기들을 보지는 않습니다. 때문에 그냥 퉁쳐서 diary라고 했습니다.

### Case 2. 쿼리스트링을 사용하는 경우

이 경우엔 이렇게 바꿀 것 같습니다.

```js
MYPAGE: {
  BASE: '/me',
  INFO: 'info',
  DIARY: 'diary',
},

// 사용 예시
`${MYPAGE.BASE}?t=${MYPAGE.INFO}`
```

t는 그냥 tap을 간단하게 줄인거고요. 그 외에 info나 diary는 Case 1과 동일하게 사용하였습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/constants/path.js
> +  WITHDRAWL: '/auth/withdrawal',
여기도 앞서 했던 리뷰와 동일하게 Update가 앞으로 나와야 할 것 같구요, withdrawal 오타가 있네요. 그리고 상수 정의 시 대문자를 사용하는 것은 맞지만, 띄어쓰기는 그냥 없애는 것이 아니라 `_`를 사용해야 합니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/DiariesByEmotion/index.jsx
> +import React from 'react';
다른 파일들에 이게 다 있더라고요. 제가 전에 다른 pr에서 리뷰한 거 보셨다고 해서 안 쓰실 줄 알았는데,, 이 import React 구문은 리액트 18 버전부터는 사용하지 않아도 됩니다. (굳이 사용하진 않는 것이 좋겠죠?)
이게 왜 있었고 어째서 지금은 필요 없는지는 알아보고 공부해두면 좋은 인사이트가 될 거라고 생각합니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +import * as S from './index.styles';
제가 eslint에서 정렬 설정을 해놔서 원래 저장하면 자동정렬되는데 지금 eslint가 제대로 먹지 않는 것 같아요. 그 부분도 한 번 확인해주세요!

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +          }}
익명함수는 자제해주세요! 바람직한 코드는 아닙니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +const Filter = ({ filters, filter, onFilterChange }) => {
이거 뒤로가기로 하면 스타일이 안먹어요! 확인하고 수정해주세요.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/57928612/236679244-31f74ee0-63c5-43e7-9a94-6400c5ed65ba.png">

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.styles.jsx
> +    transition: 0.5s ease;
transition... 사용이 뭔가 이상하네요. 공식문서에서 기본값이나 사용법 보고 바꿔보시면 좋을 것 같아요! 일단 저는 지금 상태로는 transition이 동작하지 않습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/Inputs/Button/index.jsx
> +    <>
ㅠㅠ 이것도 예전 pr에서 리뷰 남겼던 건데... 빈 태그는 자식 요소가 여러 개인데 하나로 묶는 것이 필요할 때 사용합니다. 여기선 자식 요소가 하나라서 필요하지 않습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/Inputs/Button/index.styles.jsx
> +const Button = styled.button`
딴 데는 많이 해주셨던데 여기는 transition을 안해주셨네요? 그래서 색이 갑자기 바뀌는 게 더 눈에 띄는 느낌이에요. transition을 적용하지 않은 특별한 의도가 있는 게 아니라면 적용해보면 어떨까요?

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/Inputs/index.jsx
> +        </S.Button>
버튼 안에 버튼...? (동공지진)

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/Inputs/index.jsx
> +        </S.Button>
스타일 컴포넌트 파일 보니 S.Button은 button이 아니라 div네요. 스타일 컴포넌트를 만들 때는 태그가 숨겨져 있으니 이름으로 역할을 확실히 명시해야 합니다. (저는 파일을 보기 전에 button인 줄 알고 버튼 안에 버튼... 이러고 있었어요ㅠ)
보통 이런 경우 많이 사용하는 이름으로는 ButtonWrapper 가 있겠습니다!

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +const WithdrawlModal = ({ onWithdrawl }) => {
여기도 withdrawal 오타 있습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +const WithdrawlModal = ({ onWithdrawl }) => {
근데 회원탈퇴 함수 이름이 onWithdrawal이 적절할까요? 함수 자체에 마치 핸들러 함수처럼 `on...` 이름을 붙이는 것은 '함수 이름은 함수 역할을 명시하는 것이지 함수가 어디에 쓰이는 지를 명시하는 것이 아니다'라는 클린 코드 방법에도 어긋나는 대표적인 것 중 하나이기도 하죠. 더군다나 onWithdrawal이라는 핸들러가 정말 존재하는 것도 아니구요.
저는 그냥 '탈퇴하다'라는 뜻인 `withdraw` 정도로 해도 괜찮아보입니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +              <button onClick={() => setIsModal(false)}>취소하기</button>
여기랑 위에도 익명함수 있습니다!

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +              <button onClick={() => setIsModal(false)}>취소하기</button>
모달 여는 애니메이션 넣으셨던데 만약 닫히는 애니메이션도 넣고 싶으시면 제가 만든 `useClosing` 훅을 활용하셔도 됩니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +            <S.Buttons>
Buttons...라는 이름은 적절하지 않은 것 같네요. 보통 이름을 지을 때 배열 같은 특수한 경우가 아니면 복수형은 잘 사용하지 않습니다.
Button들을 감싸고 있는 것이니 앞에 리뷰처럼 ButtonWrapper를 사용하셔도 되고, 아니면 ButtonContainer를 사용하셔도 좋겠네요.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +      {isModal && (
이제 보니까 모달을 포탈 사용하지 않고 그냥 absolute로 만드셨네요...? 왜지....? 포탈을 사용하지 않은 특별한 이유가 있나요?

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.jsx
> +      <S.Mainbutton
mainbutton이라는 한 단어가 있는 게 아니니 MainButton이라고 파스칼 케이스를 명확하게 해주는 것이 좋겠죠?

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.styles.jsx
> +  transition: background-color 0.5s ease-in-out;
color에는 일부러 transition을 주지 않으신 건가요? 배경 색만 천천히 바뀌니 애니메이션 재생이 살짝 어색하더라고요.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.styles.jsx
> +  }
keyframe은 emotion에서 따로 정의하는 방법이 있습니다. 찾아보고 적용해보시죠!

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/WithdrawlModal/index.styles.jsx
> +  }
위에 ModalWrapper도 그렇고 여기도 그렇고 부모 컴포넌트에서 자식 컴포넌트로 접근하는 스타일 코드가 너무 많으니 코드를 파악하기도 힘들고 보기도 너무 힘들어요ㅠ 분리하기 애매한 건 사용하면 좋지만 이 경우엔 분리하지 않음으로 인해 코드를 파악하기 더 힘든 상태, 득보다 실이 더 많은 상태가 되어버렸어요... 분리하면 좋을 것 같은 건 귀찮더라도 분리하는 편이 어떨까요?

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +  const [nickname, changeNickname] = useInput('');
음 저는 change에 한표입니다..! ㅎㅎ (이유는 앞에 on 관련 리뷰와 같아요!)

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +    requestEmailUpdate({ email }) //
주석표시가 있네요...

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +      .then(({ newEmail }) => {
이걸 newEmail로 보낸다고..? 뭔가 이상해서 api 문서를 가보니까 그냥 email이네요. (이러면 새로운 이메일은 무조건 undefined가 되겠네요...ㅋㅋ)
api 문서보고 여기 말고도 다른 부분이 있다면 제대로 수정해주세요. 사실 이래서 보통 먼저 api 문서 보고 msw로 응답 값을 목킹한 다음에 페이지를 만들거든요. msw 몰라 라고 내팽개치면 안돼요ㅠㅠ 재석님 안하셔서 인미님도 안하셨던데, 서버 합치기 전 오류를 미연에 방지하기 위한 프론트에서 할 수 있는 필수 안전장치입니다...

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +  const handleEmailSubmit = e => {
여기랑 밑에 함수 이름들 코멘트도 지금까지 남긴 코멘트들과 동일합니다! 함수 이름은 알아서 잘 바꿔주실거라 믿어요 :)

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +    requestNicknameUpdate({ nickname }) //
여기도 주석 표시

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +      .then(({ newNickname }) => {
얘도 이러면 undefined 뜨겠네요... api 문서 꼼꼼히 봐주세요ㅠㅠ 그리고 msw 어렵지 않거든요... 시간 되실 때 어떻게 사용하는지만 잠깐 보고 사용하시는 편이 훨씬 편하고 안전할 겁니다ㅠㅠ

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +    requestWithdrawl() //
여기도 주석이랑 withdrawal 오타요~

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +        navigate(BROWSER_PATH.BASE);
탈퇴하면 navigate 하기 전에 로그아웃이랑 토큰 삭제 등을 먼저 해야하지 않을까요..? 이대로라면 탈퇴해도 로그인 상태는 유지될텐데
useUser라는 커스텀훅을 만든 게 있는데, 거기서 탈퇴 함수를 만들어서 사용하거나 하시는 편이 좋아보입니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.jsx
> +          onNicknameSubmit={handleNicknameSubmit}
여기도 onEmailSubmit과 onNicknameSubmit이라는 prop 이름은 적절하지 않아보이네요. 그냥 changeEmail, changeNickname으로도 충분할 것 같습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/MyInfo/index.styles.jsx
> +const WrapperEdit = styled.div`
Wrapper는 앞에 붙이는 편은 아니죠.. 어차피 다른 wrapper도 없으니 그냥 Wrapper로 해도 될 것 같네요.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +const Mypage = props => {
이것도 이전 pr에 있던 리뷰긴 한데 읽는 사람 가독성을 위해서 전체적으로 import나 변수, 함수 정의 후 한 줄 띄어쓰기는 지켜주시면 좋겠습니다.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +const Mypage = props => {
근데 애초에 filters라는 건 상수네요. 또 이미 path에서 사용하는 값을 그대로 사용하고 있고요. 중복인 값을 불러오는 것이 아니라 새로운 상수로 정의해서 사용하는 것은 좋지 않아보여요.

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +      <Title name={'마이페이지'} />
문자열에는 `{}`를 사용하지 않아도 됩니다. (아까와 마찬가지로, 사용하지 않는 편이 좋겠죠)

2023-05-07 13:56 UTC, LAH1203 commented on src/pages/Signup/index.jsx
> -
엔터 일부러 넣었던건데...ㅠ (전 가독성이 최고라)

2023-05-14 06:51 UTC, LAH1203 requested changes
코드가 많이 깔끔해졌네요! 지금도 좋지만, 더 발전할 여지가 보여서 한번 더 request change 남겨봅니다...ㅎㅎ
이번 거는 큰 건 없어서, 금방 확인하실 것 같아요! 그리고 이유 여쭤본 건 정말 이유가 궁금했던 것도 섞여있고, 의도가 뭔지가 궁금했던 것도 있어서 답 남겨주시면 좋을 것 같아요~

2023-05-14 06:51 UTC, LAH1203 commented on src/hooks/useUser.js
> +    logout();
회원탈퇴에서 로그아웃 함수를 호출하는 부분밖에 없네요.이러면 logout을 쓰는 것과 다를 바가 없을 것 같아요.
이러면은 차라리 withdraw 함수 없이 logout 함수를 호출하거나 아니면 withdraw 함수에 회원탈퇴 api 요청 부분을 넣는 방법이 좋을 것 같아요. 만약 api를 넣는다면 api 성공 또는 실패 여부에 따라 에러를 던지거나 응답값을 다르게 하는 등 사용하는 컴포넌트에서 결과를 알 수 있는 값을 같이 보내는거죠. 그럼 사용부에서는 그걸 보고 결과를 사용자에게 보여주면 되는..? 그런 방식으로 사용할 수 있을 것 같아요! 로직 분리도 되구요.
둘 중 괜찮을 것 같은 방법으로 바꾸면 좋을 것 같아요!

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +const Filter = ({ filter, filterChange }) => {
실례가 안된다면 여기랑 다른 파일들 import랑 컴포넌트 사이에 엔터 하나만… 구분이 안가요ㅠ

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +    filterChange(BROWSER_PATH.MYPAGE.INFO);
보통 함수명은 직관적으로 알 수 있게 명사형보다는 동사형을 쓴다고 저번 리뷰에서 말씀드렸었는데, 여기도 같은 맥락입니다! change와 filter 위치를 바꾸면 좋겠네요 :)

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Filter/index.jsx
> +    filterChange(BROWSER_PATH.MYPAGE.INFO);
추가적으로, changeFilterToInfo와 changeFilterToDiary는 비슷한 점이 많다고 생각되지 않나요? 이런 경우 커링을 활용하면 매우 좋습니다. 커링도 잘 사용하면 너무 좋은 기술이라 어디에 활용하면 좋을지, 어떻게 활용하면 내 코드가 고도화될지 꾸준히 고민하는 것도 좋을 것 같아요. 지금은 공부하는 단계니 이곳에 커링을 어떻게 적용할지 코드를 적고 가겠습니다! 다음 pr에서는 커링을 어떻게 활용하실지 기대하겠습니다 :)

```js
const changePageFilter = filter => () => {
  filterChange(filter);
};

onClick={changePageFilter(BROWSER_PATH.MYPAGE.INFO)}
onClick={changePageFilter(BROWSER_PATH.MYPAGE.DIARY)}
```

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Info/WithdrawalModal/index.jsx
> +      <Portal to="modal">
구조가 조금 특이하네요...? 포탈을 이렇게 사용하신 이유가 있나요?

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Info/WithdrawalModal/index.jsx
> +  const onModal = () => {
여기도 onModal offModal 에 커링을 적용할 수 있겠네요

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Info/WithdrawalModal/index.jsx
> +            <S.ModalWrapper>
궁금한 게 container와 wrapper 사이에는 아무것도 없는데 왜 나누신건가요? 하나로는 스타일 적용이 안됐나요?

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +import { useNavigate, useSearchParams } from 'react-router-dom';
뭐지… eslint에서 import 자동 정렬 설정해놨는데 왜 안먹을까요…ㅠㅠ

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +  const filterChange = boolean => {
문자열 방식으로 인자가 넘어오니까 boolean이라는 이름은 적절하지 않은 것 같네요

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +import Filter from '@/pages/Mypage/Filter';
제가 노션에 문서로 정리도 해놨었고(혹시 안보셨다면 봐주세요) 지금까지 한 것들에서는 각 파일 이름은 index로 해왔었거든요! 근데 지금 보니 인미님이 해주신건 조금 다른 것 같아요. 음… 특별한 이유가 있는 게 아니면 컨벤션을 맞춰주시면 감사하겠습니다! ㅎㅎ

2023-05-14 06:51 UTC, LAH1203 commented on src/hooks/useInput.js
> +  const replaceValue = value => {
그냥 setValue 호출 함수네요...? 입력값 검증 같은 로직이 있는 게 아니면 굳이 감싸서 새로운 함수를 만들 필요 없이 setValue를 반환해서 사용해도 될 것 같아요. 대신 무작정 setValue를 박아버리면 위험하니 dangerouslySetValue 같이 위험성을 암시하는 이름을 붙여주면 좋을 것 같구요!

2023-05-14 06:51 UTC, LAH1203 commented on src/hooks/useInput.js
> +  return [value, onChangeValue, resetValue, replaceValue];
그리고 여기는 이제 반환값이 많아져서 배열보다는 객체로 바꾸는 것이 적절할 것 같은데, 다른 파일들에서 많이 사용하고 있어서 수정이 조금 많아지겠네요…ㅎ

2023-05-14 06:51 UTC, LAH1203 commented on src/mocks/handlers/auth.js
> +    return res(ctx.status(200));
삭제 성공 응답값이 200인가요…? 혹시 문서도 200으로 하신건 아니겠죠..?
rest api에선 생성은 201, 삭제는 204로 성공 응답을 보내는 게 일반적이에요!

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/Info/index.jsx
> +  const [email, changeEmail, , replaceEmail] = useInput('');
이런거 때문이라도 useInput 리턴값을 객체로 바꿔야겠네요…

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +    switch (searchParams.get('t')) {
어차피 둘 중 하나니 그냥 if문 쓰는 게 깔끔할 것 같네요

```js
const { INFO, DIARY } = BROWSER.PATH.MYPAGE;

if (searchParams.get('t') === DIARY) {
  setFilter(DIARY);

  return;
}

setFilter(INFO);
```

2023-05-14 06:51 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +      {filter === BROWSER_PATH.MYPAGE.DIARY && <Diary />}
여기도 둘 중 하나니 삼항연산자가 깔끔해보여요

```js
{filter === BROWSER.PATH.MYPAGE.INFO ? <Info /> : <Diary />}
```

2023-05-14 13:15 UTC, Pridesd reviewed
고생하셨습니당

2023-05-14 13:15 UTC, Pridesd commented on src/pages/Mypage/Filter/index.jsx
> +          className={filter === BROWSER_PATH.MYPAGE.INFO ? 'selected' : ''}
이거는 그냥 궁금해서 여쭤보는 건데 styled component를 쓰는 상황에서 className을 쓰는 게 더 편하신가요 아니면 props값을 보내서 사용하는 방법이 더 편하신가요?

2023-05-14 13:15 UTC, Pridesd commented on src/pages/Mypage/Info/index.jsx
> +      alert('입력값을 확인해주세요.');
이거도 그냥 constant message로 설정하는 건 어떤가용

2023-05-14 13:15 UTC, Pridesd commented on src/pages/Mypage/Info/index.jsx
> +  const [email, changeEmail, , replaceEmail] = useInput('');
홀리몰리

2023-05-16 13:35 UTC, Pridesd approved these changes
고생하셨습니다!

2023-05-17 03:40 UTC, LAH1203 approved these changes
추가적인 수정이 필요해 보이는 부분 몇 개 더 달았는데요! 그 외에는 딱히 문제가 되거나 하는 부분은 지금으로선 보이지 않네요ㅎㅎ
저는 일단 바로 approve 드릴테니, 추가적인 코멘트 확인하고 수정하시고 나면 머지하셔도 될 것 같습니다 !
수고하셨습니다~🙂

2023-05-17 03:40 UTC, LAH1203 commented on src/hooks/useInput.js
> +  return { value, onChangeValue, resetValue, dangerouslySetValue };
앗... 제 의견은 dangerouslySetValue 함수를 새롭게 만드는 게 아니라 객체를 내보낼 때 키값을 dangerouslySetValue로 주는 것이었습니다...ㅎ

```js
return { value, onChangeValue, resetValue, dangerouslySetValue: setValue };
```

2023-05-17 03:40 UTC, LAH1203 commented on src/pages/Mypage/Info/WithdrawalModal/index.jsx
>    };
개인적인 의견으로는 boolean이라는 이름은 직관적이지 않고 타입 이름이기도 하니 (방금 보고 무슨 코드였지 1분 생각했어요..ㅎㅎㅎ) isModal 이름을 그대로 사용해도 괜찮겠다는 생각이 드네요!

2023-05-17 03:40 UTC, LAH1203 commented on src/pages/Mypage/Info/WithdrawalModal/index.jsx
> +                </S.CancelButton>
(아 이 부분은 제가 못봤었네요.. 혹시 다른 곳에도 이런 식으로 사용한 게 있다면 수정해주세요!)

button의 기본 타입은 submit입니다. 근데 여기서는 그냥 button으로 사용했죠? 그러면 type이 button임을 명시해야 합니다.

2023-05-17 03:40 UTC, LAH1203 commented on src/pages/Mypage/index.jsx
> +    setFilter(INFO);
어차피 searchParams.get('t')가 DIARY가 아니면 전부 INFO 잖아요? 이럴 땐 예외처리를 먼저 하면 깔끔합니다. 저번 리뷰에서 적었던 것 같은데,,, 제대로 못보셨나 싶어서 한번 더 적어봐요!

```js
if (searchParams.get('t') === DIARY) {
  setFilter(DIARY);
  
  return;
}

setFilter(INFO);
```

2023-05-17 11:31 UTC, rewritestar commented
많이 배웠습니다...다음부터 더 좋은 코드 짜볼게요!

2023-05-17 11:31 UTC, merged